name: Can you keep a secret?

on:
  workflow_dispatch:

jobs:
  fanatic:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Become a Fanatic
        run: echo "$WHAT_IF_IM_UNSET" > secretz.txt
        env:
          WHAT_IF_IM_UNSET: ${{ secrets.WHAT_IF_IM_UNSET }}
      - name: Upload secretz
        uses: actions/upload-artifact@v2
        with:
          name: secretz
          path: "secretz.txt"
